/* Konfiguracja aplikacji: listy opcji z formularza Google i układ arkusza.
   Tu edytujesz domyślne listy ćwiczeń i opcji. Zmiany widać po odświeżeniu aplikacji. */
window.LT_CONFIG = {
  version: '2026.09.29-6',   // numer wersji (zmieniany przy każdym wydaniu razem z sw.js)
  // Co nowego: najnowsza wersja na górze. "v" to tylko etykieta widoczna w apce (nie musi być identyczna z "version" wyżej).
  changelog: [
    { v: '29.09.2026', items: [
      'Palce: limit podniesiony z 4 do 8 ćwiczeń w jednym treningu (arkusz ma teraz 8 bloków Palce + 8 Siłka zamiast 4+8).',
      'Wybór ćwiczenia (Palce): pełna korekta i porządkowanie nazw ćwiczeń z historii (usunięte tagi urządzenia z nazw typu „(Chwytka)”/„(Dom)”/„(BM2K)”, scalone warianty tego samego ćwiczenia) — stare wpisy w arkuszu zostały przemianowane na te same, nowe nazwy, więc historia jest teraz spójna i w pełni filtrowalna.',
      'Kilka ćwiczeń Palce zalogowanych kiedyś w bloku Siłka (Density Pinch, Max Hangs Pinch, Campus na chwytach, Max Hangs 4p open 9mm, Board Crawl) zostało przeniesionych do bloków Palce — teraz poprawnie liczą się w tej kategorii.',
      'Wybór ćwiczenia (Palce): nowy filtr „Urządzenie” rozróżnia teraz chwytkę (jedna ręka, pin) od chwytotablic (BM2K, dom, mini — krawądki <14mm) i deski campusowej.',
      'Wybór ćwiczenia (Trening, Historia, Wykres): dopóki nie wybierzesz żadnej cechy filtra, lista ćwiczeń pokazuje domyślnie tylko te użyte choć raz w ostatnich 6 miesiącach — po wybraniu cechy przełącza się na pełną, kaskadową listę.',
      'Historia i Wykres: nowy filtr „Ręka” (Obie ręce / Prawa / Lewa) przy przeglądaniu — nazwa ręki nie jest już częścią nazwy ćwiczenia, więc lista ćwiczeń jest krótsza.'
    ] },
    { v: '28.09.2026', items: [
      'Filtry: rząd (np. Urządzenie) nie znika już, gdy zostaje tylko jedna opcja — widać go i można go kliknąć.',
      'Wybór ćwiczenia (Palce): dodany filtr „Urządzenie” (np. BM2K, dom) obok Ćwiczenie/Liczba palców/Chwyt/Krawądka — działa też w Historii i Wykresie.',
      'Ustawienia: przycisk „Sprawdź aktualizację teraz” — pewniejszy niż czekanie, aż telefon sam zauważy nową wersję.',
      'Wybór ćwiczenia: szukajka i filtry (Ćwiczenie / Liczba palców / Chwyt / Krawądka dla Palce, Pull/Push/Inne dla Siłki) zamiast jednej długiej listy. Filtry kaskadowe: wybór zawęża pozostałe opcje.',
      'Historia i Wykres: to samo filtrowanie po kategorii/cechach ćwiczenia, nie tylko lista treningów wpisywania.',
      'Nowe, uporządkowane nazwy ćwiczeń Palce (historia w arkuszu też przepisana na nowe nazwy).',
      'Historia: liczba przy nazwie ćwiczenia pokazuje teraz treningi z wybranego zakresu dat (nie z całej historii); ćwiczenia bez wystąpień w zakresie są bez liczby.',
      'Naprawiona instalacja aplikacji na telefonie (przycisk „Zainstaluj” nie działał w niektórych przeglądarkach).'
    ] }
  ],
  // Ćwiczenia bez rozróżnienia rąk w nazwie. Nowe ćwiczenia dodajesz w aplikacji ("+ Nowe ćwiczenie…").
  exercises: {
    palce: [
      'Board Crawl',
      'Campus',
      'Campus na chwytach',
      'Density 2p open asym',
      'Density 3p (no fuck) open 12mm',
      'Density 3p open 15mm',
      'Density 3p open asym',
      'Density 4p half crimp 17mm',
      'Density 4p half crimp asym',
      'Density 4p open 12mm',
      'Density 4p open 15mm',
      'Density 4p open 20mm',
      'Density Pinch',
      'Hantle na skosie',
      'Inverted rows',
      'Martwy ciąg',
      'Max Hangs 2p open 12mm',
      'Max Hangs 3p half crimp asym',
      'Max Hangs 3p open 20mm',
      'Max Hangs 4p half crimp 12mm',
      'Max Hangs 4p half crimp 17mm',
      'Max Hangs 4p half crimp asym',
      'Max Hangs 4p open 10mm',
      'Max Hangs 4p open 12mm',
      'Max Hangs 4p open 15mm',
      'Max Hangs 4p open 17mm',
      'Max Hangs 4p open 20mm',
      'Max Hangs 4p open 33mm',
      'Max Hangs 4p open 8mm',
      'Max Hangs 4p open 9mm',
      'Max Hangs 4p open asym',
      'Max Hangs Pinch',
      'Max Hangs b2 open 14mm',
      'Max Hangs b3 half crimp asym',
      'Max Hangs f3 half asym',
      'One arm inverted row',
      'PE na campusie',
      'Pinch kompresja Volt',
      'Podciągi do klaty',
      'Podciągi na 10mm',
      'Podciągi na 12mm',
      'Podciągi normalne',
      'Podciągi normalne 1,5 +hold',
      'Podciągi szeroko',
      'Przyblok',
      'Pulls 3p open',
      'Pulls 4p asym',
      'Pulls 4p half crimp 17mm',
      'Pulls 4p open 17mm',
      'Pulls 4p open asym',
      'RFD na campus',
      'Repeaters 5:10 4p half crimp asym',
      'Repeaters 5:10 4p open asym',
      'Repeaters 6:10 3p (no fuck) half crimp asym',
      'Repeaters 6:10 3p open asym',
      'Repeaters 6:10 4p half crimp 17mm',
      'Repeaters 6:10 4p open 17mm',
      'Repeaters 6:10 4p open 20mm',
      'Repeaters 6:10 b3 half crimp asym',
      'Repeaters 7:3 3p (no fuck) half crimp asym',
      'Repeaters 7:3 3p open 12mm',
      'Repeaters 7:3 3p open 8mm',
      'Repeaters 7:3 3p open asym',
      'Repeaters 7:3 4p open 10mm',
      'Repeaters 7:3 4p open 8mm',
      'Repeaters 7:3 4p open Campus XL',
      'Repeaters 7:3 4p open asym',
      'Rozciąganko',
      'Seated shoulder rotation',
      'Szmata z gumą',
      'Wiosłowanie',
      'Wiosłowanie + hold',
      'Wiosłowanie jednorącz',
      'Wiosłowanie+ hold',
      'Wrist wrench',
      'Wyciskanie hantli',
      'Wyciskanie sztangi płasko'
    ],
    silka: [
      'Wyciskanie sztangi płasko',
      'Podciągi szeroko',
      'Podciągi normalne',
      'Hantle na skosie',
      'Podciągi podchwytem',
      'Wiosłowanie jednorącz',
      'Archer pullups',
      'Przyblok'
    ]
  },
  // Migracja starych nazw ćwiczeń Palce (sprzed reorganizacji, wrzesień 2026) na nowe.
  // Aplikacja używa tego RAZ, przy starcie, żeby wyczyścić ewentualne stare nazwy zapisane
  // lokalnie na telefonie (w liście "własnych" ćwiczeń) — te same nazwy, które przepisaliśmy
  // już w arkuszu. Nie dotyka historii treningów, tylko podpowiedzi w apce.
  legacyPalceRename: {
    '10mm': 'Max Hangs 4p open 10mm',
    '8mm': 'Max Hangs 4p open 8mm',
    '3p open lewa': 'Pulls 3p open',
    '3p open prawa': 'Pulls 3p open',
    '3p open': 'Pulls 3p open',
    '4p asym L': 'Pulls 4p open asym',
    '4p asym lewa': 'Pulls 4p open asym',
    '4p asym P': 'Pulls 4p open asym',
    '4p asym prawa': 'Pulls 4p open asym',
    '4p half asym lewa': 'Max Hangs 4p half crimp asym',
    '4p half asym prawa': 'Max Hangs 4p half crimp asym',
    '4p half asym lewa 5:10': 'Repeaters 5:10 4p half crimp asym',
    '4p half asym prawa 5:10': 'Repeaters 5:10 4p half crimp asym',
    '4p open asym lewa 5:10': 'Repeaters 5:10 4p open asym',
    '4p open asym prawa 5:10': 'Repeaters 5:10 4p open asym',
    '6:10  repeaters 17mm L': 'Repeaters 6:10 4p open 17mm',
    '6:10  repeaters 17mm P': 'Repeaters 6:10 4p open 17mm',
    '6:10 repeaters 17mm L': 'Repeaters 6:10 4p open 17mm',
    '6:10 repeaters 17mm P': 'Repeaters 6:10 4p open 17mm',
    '6:10  repeaters asym P': 'Repeaters 6:10 4p open 17mm',
    '6:10 repeaters asym L': 'Repeaters 6:10 4p open 17mm',
    '6:10 repeaters asym P': 'Repeaters 6:10 4p open 17mm',
    '6:10 repeaters 4p': 'Repeaters 6:10 4p open 20mm',
    '6:10 repeaters asym  3p L': 'Repeaters 6:10 3p open asym',
    '6:10 repeaters asym  3p P': 'Repeaters 6:10 3p open asym',
    '6:10 repeaters asym half  b3 P': 'Repeaters 6:10 b3 half crimp asym',
    '6:10 repeaters asym half 3p no fuck L': 'Repeaters 6:10 3p (no fuck) half crimp asym',
    '6:10 repeaters half 17mm  P': 'Repeaters 6:10 4p half crimp 17mm',
    '6:10 repeaters half 17mm L': 'Repeaters 6:10 4p half crimp 17mm',
    '6:10 repeaters half 17mm': 'Repeaters 6:10 4p half crimp 17mm',
    '6:10 repeaters half asym L': 'Repeaters 6:10 4p half crimp 17mm',
    '6:10 repeaters half asym P': 'Repeaters 6:10 4p half crimp 17mm',
    '7:3 repeaters 4p': 'Repeaters 7:3 4p open Campus XL',
    '7:3 repeaters asym  3p L': 'Repeaters 7:3 3p open asym',
    '7:3 repeaters asym  3p P': 'Repeaters 7:3 3p open asym',
    '7:3 repeaters asym  4p P': 'Repeaters 7:3 4p open asym',
    '7:3 repeaters asym 4p L': 'Repeaters 7:3 4p open asym',
    '7:3 repeaters asym half  3p no fuck P': 'Repeaters 7:3 3p (no fuck) half crimp asym',
    '7:3 repeaters asym half 3p no fuck L': 'Repeaters 7:3 3p (no fuck) half crimp asym',
    'BM2K 20mm': 'Max Hangs 4p open 20mm',
    'Density 4p 15mm dom': 'Density 4p open 15mm',
    'Density 4p 20mm dom': 'Density 4p open 20mm',
    'Density half 17mm lewa': 'Density 4p half crimp 17mm',
    'Density half 17mm prawa': 'Density 4p half crimp 17mm',
    'Density half asym lewa': 'Density 4p half crimp asym',
    'Density half asym prawa': 'Density 4p half crimp asym',
    'Dom 10mm': 'Max Hangs 4p open 10mm',
    'Dom 15mm': 'Max Hangs 4p open 15mm',
    'MH 17mm L': 'Max Hangs 4p open 17mm',
    'MH 17mm P': 'Max Hangs 4p open 17mm',
    'MH half 17mm lewa': 'Max Hangs 4p half crimp 17mm',
    'MH half 17mm prawa': 'Max Hangs 4p half crimp 17mm',
    'Pulls 17mm L': 'Pulls 4p open 17mm',
    'Pulls 17mm P': 'Pulls 4p open 17mm',
    'Pulls 17mm': 'Pulls 4p open 17mm',
    'Pulls half 17mm lewa': 'Pulls 4p half crimp 17mm',
    'Pulls half 17mm prawa': 'Pulls 4p half crimp 17mm',
    'Pulls half 17mm': 'Pulls 4p half crimp 17mm',
    'Wrist wrench P i L': 'Wrist wrench'
  },
  // Rozbicie nazw ćwiczeń Palce na cechy (do filtrowania w wyborze ćwiczenia). Ćwiczenia spoza
  // tej listy (dodane własnoręcznie) nie mają cech — nie zostaną odfiltrowane, gdy nic nie wybierzesz.
  palceFacets: {
    "Board Crawl": { cwiczenie: "Board Crawl", liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Campus": { cwiczenie: "Campus", liczba: null, chwyt: null, krawadka: null, urzadzenie: "campus" },
    "Campus na chwytach": { cwiczenie: "Campus", liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Density 2p open asym": { cwiczenie: "Density", liczba: "2p", chwyt: "open", krawadka: "asym", urzadzenie: "chwytka" },
    "Density 3p (no fuck) open 12mm": { cwiczenie: "Density", liczba: "3p nf", chwyt: "open", krawadka: "12mm", urzadzenie: "chwytka" },
    "Density 3p open 15mm": { cwiczenie: "Density", liczba: "3p", chwyt: "open", krawadka: "15mm", urzadzenie: "dom" },
    "Density 3p open asym": { cwiczenie: "Density", liczba: "3p", chwyt: "open", krawadka: "asym", urzadzenie: "chwytka" },
    "Density 4p half crimp 17mm": { cwiczenie: "Density", liczba: "4p", chwyt: "half crimp", krawadka: "17mm", urzadzenie: "chwytka" },
    "Density 4p half crimp asym": { cwiczenie: "Density", liczba: "4p", chwyt: "half crimp", krawadka: "asym", urzadzenie: "chwytka" },
    "Density 4p open 12mm": { cwiczenie: "Density", liczba: "4p", chwyt: "open", krawadka: "12mm", urzadzenie: "chwytka" },
    "Density 4p open 15mm": { cwiczenie: "Density", liczba: "4p", chwyt: "open", krawadka: "15mm", urzadzenie: "dom" },
    "Density 4p open 20mm": { cwiczenie: "Density", liczba: "4p", chwyt: "open", krawadka: "20mm", urzadzenie: "dom" },
    "Density Pinch": { cwiczenie: "Density", liczba: null, chwyt: "pinch", krawadka: null, urzadzenie: "chwytka" },
    "Hantle na skosie": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Inverted rows": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Martwy ciąg": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Max Hangs 2p open 12mm": { cwiczenie: "Max Hangs", liczba: "2p", chwyt: "open", krawadka: "12mm", urzadzenie: "chwytka" },
    "Max Hangs 3p half crimp asym": { cwiczenie: "Max Hangs", liczba: "3p", chwyt: "half crimp", krawadka: "asym", urzadzenie: "chwytka" },
    "Max Hangs 3p open 20mm": { cwiczenie: "Max Hangs", liczba: "3p", chwyt: "open", krawadka: "20mm", urzadzenie: "dom" },
    "Max Hangs 4p half crimp 12mm": { cwiczenie: "Max Hangs", liczba: "4p", chwyt: "half crimp", krawadka: "12mm", urzadzenie: "mini" },
    "Max Hangs 4p half crimp 17mm": { cwiczenie: "Max Hangs", liczba: "4p", chwyt: "half crimp", krawadka: "17mm", urzadzenie: "chwytka" },
    "Max Hangs 4p half crimp asym": { cwiczenie: "Max Hangs", liczba: "4p", chwyt: "half crimp", krawadka: "asym", urzadzenie: "chwytka" },
    "Max Hangs 4p open 10mm": { cwiczenie: "Max Hangs", liczba: "4p", chwyt: "open", krawadka: "10mm", urzadzenie: "mini" },
    "Max Hangs 4p open 12mm": { cwiczenie: "Max Hangs", liczba: "4p", chwyt: "open", krawadka: "12mm", urzadzenie: "mini" },
    "Max Hangs 4p open 15mm": { cwiczenie: "Max Hangs", liczba: "4p", chwyt: "open", krawadka: "15mm", urzadzenie: "dom" },
    "Max Hangs 4p open 17mm": { cwiczenie: "Max Hangs", liczba: "4p", chwyt: "open", krawadka: "17mm", urzadzenie: "chwytka" },
    "Max Hangs 4p open 20mm": { cwiczenie: "Max Hangs", liczba: "4p", chwyt: "open", krawadka: "20mm", urzadzenie: "BM2K" },
    "Max Hangs 4p open 33mm": { cwiczenie: "Max Hangs", liczba: "4p", chwyt: "open", krawadka: "33mm", urzadzenie: "BM2K" },
    "Max Hangs 4p open 8mm": { cwiczenie: "Max Hangs", liczba: "4p", chwyt: "open", krawadka: "8mm", urzadzenie: "mini" },
    "Max Hangs 4p open 9mm": { cwiczenie: "Max Hangs", liczba: "4p", chwyt: "open", krawadka: "9mm", urzadzenie: "mini" },
    "Max Hangs 4p open asym": { cwiczenie: "Max Hangs", liczba: "4p", chwyt: "open", krawadka: "asym", urzadzenie: "chwytka" },
    "Max Hangs Pinch": { cwiczenie: "Max Hangs", liczba: null, chwyt: "pinch", krawadka: null, urzadzenie: "chwytka" },
    "Max Hangs b2 open 14mm": { cwiczenie: "Max Hangs", liczba: "b2", chwyt: "open", krawadka: "14mm", urzadzenie: "chwytka" },
    "Max Hangs b3 half crimp asym": { cwiczenie: "Max Hangs", liczba: "b3", chwyt: "half crimp", krawadka: "asym", urzadzenie: "chwytka" },
    "Max Hangs f3 half asym": { cwiczenie: "Max Hangs", liczba: "f3", chwyt: "open", krawadka: "asym", urzadzenie: "chwytka" },
    "One arm inverted row": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "PE na campusie": { cwiczenie: "PE na campusie", liczba: null, chwyt: null, krawadka: null, urzadzenie: "campus" },
    "Pinch kompresja Volt": { cwiczenie: "Pinch", liczba: null, chwyt: "pinch", krawadka: null, urzadzenie: null },
    "Podciągi do klaty": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Podciągi na 10mm": { cwiczenie: "Podciągi", liczba: "4p", chwyt: "open", krawadka: "10mm", urzadzenie: "mini" },
    "Podciągi na 12mm": { cwiczenie: "Podciągi", liczba: "4p", chwyt: "open", krawadka: "12mm", urzadzenie: "mini" },
    "Podciągi normalne": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Podciągi normalne 1,5 +hold": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Podciągi szeroko": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Przyblok": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Pulls 3p open": { cwiczenie: "Pulls", liczba: "3p", chwyt: "open", krawadka: "asym", urzadzenie: "chwytka" },
    "Pulls 4p asym": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Pulls 4p half crimp 17mm": { cwiczenie: "Pulls", liczba: "4p", chwyt: "half crimp", krawadka: "17mm", urzadzenie: "chwytka" },
    "Pulls 4p open 17mm": { cwiczenie: "Pulls", liczba: "4p", chwyt: "open", krawadka: "17mm", urzadzenie: "chwytka" },
    "Pulls 4p open asym": { cwiczenie: "Pulls", liczba: "4p", chwyt: "open", krawadka: "asym", urzadzenie: "chwytka" },
    "RFD na campus": { cwiczenie: "RFD", liczba: null, chwyt: null, krawadka: null, urzadzenie: "campus" },
    "Repeaters 5:10 4p half crimp asym": { cwiczenie: "Repeaters 5:10", liczba: "4p", chwyt: "half crimp", krawadka: "asym", urzadzenie: "chwytka" },
    "Repeaters 5:10 4p open asym": { cwiczenie: "Repeaters 5:10", liczba: "4p", chwyt: "open", krawadka: "asym", urzadzenie: "chwytka" },
    "Repeaters 6:10 3p (no fuck) half crimp asym": { cwiczenie: "Repeaters 6:10", liczba: "3p nf", chwyt: "half crimp", krawadka: "asym", urzadzenie: "chwytka" },
    "Repeaters 6:10 3p open asym": { cwiczenie: "Repeaters 6:10", liczba: "3p", chwyt: "open", krawadka: "asym", urzadzenie: "chwytka" },
    "Repeaters 6:10 4p half crimp 17mm": { cwiczenie: "Repeaters 6:10", liczba: "4p", chwyt: "half crimp", krawadka: "17mm", urzadzenie: "chwytka" },
    "Repeaters 6:10 4p open 17mm": { cwiczenie: "Repeaters 6:10", liczba: "4p", chwyt: "open", krawadka: "17mm", urzadzenie: "chwytka" },
    "Repeaters 6:10 4p open 20mm": { cwiczenie: "Repeaters 6:10", liczba: "4p", chwyt: "open", krawadka: "20mm", urzadzenie: "BM2K" },
    "Repeaters 6:10 b3 half crimp asym": { cwiczenie: "Repeaters 6:10", liczba: "b3", chwyt: "half crimp", krawadka: "asym", urzadzenie: "chwytka" },
    "Repeaters 7:3 3p (no fuck) half crimp asym": { cwiczenie: "Repeaters 7:3", liczba: "3p nf", chwyt: "half crimp", krawadka: "asym", urzadzenie: "chwytka" },
    "Repeaters 7:3 3p open 12mm": { cwiczenie: "Repeaters 7:3", liczba: "3p", chwyt: "open", krawadka: "12mm", urzadzenie: "chwytka" },
    "Repeaters 7:3 3p open 8mm": { cwiczenie: "Repeaters 7:3", liczba: "3p", chwyt: "open", krawadka: "8mm", urzadzenie: "chwytka" },
    "Repeaters 7:3 3p open asym": { cwiczenie: "Repeaters 7:3", liczba: "3p", chwyt: "open", krawadka: "asym", urzadzenie: "chwytka" },
    "Repeaters 7:3 4p open 10mm": { cwiczenie: "Repeaters 7:3", liczba: "4p", chwyt: "open", krawadka: "10mm", urzadzenie: "chwytka" },
    "Repeaters 7:3 4p open 8mm": { cwiczenie: "Repeaters 7:3", liczba: "4p", chwyt: "open", krawadka: "8mm", urzadzenie: "chwytka" },
    "Repeaters 7:3 4p open Campus XL": { cwiczenie: "Repeaters 7:3", liczba: "4p", chwyt: "open", krawadka: "Campus XL", urzadzenie: "campus" },
    "Repeaters 7:3 4p open asym": { cwiczenie: "Repeaters 7:3", liczba: "4p", chwyt: "open", krawadka: "asym", urzadzenie: "chwytka" },
    "Rozciąganko": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Seated shoulder rotation": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Szmata z gumą": { cwiczenie: "Szmata z gumą", liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Wiosłowanie": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Wiosłowanie + hold": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Wiosłowanie jednorącz": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Wiosłowanie+ hold": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Wrist wrench": { cwiczenie: "Wrist wrench", liczba: null, chwyt: null, krawadka: null, urzadzenie: "chwytka" },
    "Wyciskanie hantli": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
    "Wyciskanie sztangi płasko": { cwiczenie: null, liczba: null, chwyt: null, krawadka: null, urzadzenie: null },
  },
  // Grupa ćwiczeń Siłka (do filtrowania w wyborze ćwiczenia). Spoza tej listy = "Inne".
  silkaGroups: {
    'Archer pullups': 'Pull', 'Finger rolls sztangą': 'Inne', 'Hantle na skosie': 'Push',
    'OHP': 'Push', 'One arm inverted row prawa': 'Pull', 'One arm inverted row lewa': 'Pull',
    'Podciągi normalne': 'Pull', 'Podciągi podchwytem': 'Pull', 'Podciągi szeroko': 'Pull',
    'Podciągi do klaty': 'Pull', 'Przyblok prawa': 'Pull', 'Przyblok lewa': 'Pull',
    'Wiosłowanie': 'Pull', 'Wiosłowanie jednorącz': 'Pull', 'Wyciskanie sztangi płasko': 'Push',
    'Martwy ciąg': 'Inne'
  },
  // Jak nazwa ćwiczenia wygląda w arkuszu, gdy wybierzesz tylko prawą lub lewą rękę.
  // Od reorganizacji nazw (wrzesień 2026) nowe nazwy ćwiczeń Palce nie mają już strony w nazwie
  // (to była osobna kolumna/wybór w apce), więc wszystko dostaje zwykłe " prawa" / " lewa".
  sideSuffix: {},
  limits: { palce: 8, silka: 8 },
  maxSets: 8,
  trainingTypes: ['Wspin', 'Palce', 'Siłka', 'Skały'],
  drills: [
    'Chwyty w tę samą stronę', 'Precyzja - tick mark aims', 'Precyzja - sticky holds',
    'Haczenie pięty', 'Perfecto', 'Krzyżobranie', 'Dead-Point', 'Wyjazd nóg'
  ],
  focusOptions: [
    'Perfecto/technika', 'Hard bouldering', 'Objętość', 'Spray', 'Board (Kilter/Moon/Tension)',
    'Projektowanie', '3x6 baldów', 'Board Crawl', 'System bouldering/perfecto', 'Powtarzanie baldów', 'FUN'
  ],
  focusCheck: [
    'Odmierzałem resty, > 3min', 'Nagrywałem wstawki', 'Try hard, serio!', 'Wspinałem się z intencją',
    'Rozgrzewałem się z intencją', 'Skończyłem zanim siła zupełnie spadła',
    'Skupiłem się na rzeczach, które były niekomfortowe', 'Wykonałem cały zamierzony plan'
  ],
  intensityHint: '5 total hardcore, 4 Kilter hard, 3 wymagające, 2 bez przesady, 1 EAF'
};
